### ISSUE TITLE
React Canvas help!

### ISSUE THREAD

**Issue by Semiosphere** [bor3ham/react-canvas-map#25]
I'm new to Github (and coding, to be honest) so forgive me if this is a totally inappropriate way to reach out to you.

I'm working on a small web app where a user can pan around a hand-drawn map and click on different icons to read more about the clicked location. I found this project and it was a perfect fit for what I need but I'm struggling to style the tool tip boxes the way I need. 

I was wondering if you would be able to offer any suggestions. I have a wireframe I'd be happy to show you to demonstrate my end goal. Either way, thanks for publishing this project! I hope it helps a lot of developers!

**Comment by bor3ham** [comment]
Hey no problem, glad you're getting some use from the package!

I see what you mean - I rushed getting the tooltips working for a client so the styles were all inline and unchangeable. I've published a new version `0.1.8` with no inline styles on the tooltips, styling instead being implemented with css.

It's still not the greatest solution for customisation of the tooltips - but you should be able to make basic adjustments with css rules on `.div.RCMAP-tooltip`.

You'll just have to include the new css dist file in `node_modules/react-canvas-map/dist/react-canvas-map.css` or entirely implement your own version of the css rules [found here](https://github.com/bor3ham/react-canvas-map/blob/master/src/index.css).

**Comment by Semiosphere** [comment]
This is great! Thanks Michael!
