### ISSUE TITLE
Does scaleWithZoom work in Markers?

### ISSUE THREAD

**Issue by ceebs-bdh** [bor3ham/react-canvas-map#26]
Perhaps I am misunderstanding its intended functionality but `scaleWithZoom` doesn't seem to work for me. When I zoom further into the canvas, the Marker Icon grows in size (until it's ridiculously big and covers way too much canvas/map area). My understanding is that the marker icon should remain the same size relative to the zoom/scale of the canvas?

**Comment by bor3ham** [comment]
Hey it sounds like what you want is for it to _not_ scale with zoom - it defaults to on, so give `scaleWithZoom={false}` a try

**Comment by ceebs-bdh** [comment]
Woops, that's exactly what I want, thanks!
